
import java.awt.Rectangle;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jeanp
 */
public class cargarArchivo extends javax.swing.JFrame {

    private static File[] archivos;
    boolean archivoValido = false;
    ArrayList<String[]> espaciosMemoria = new ArrayList<>(100);
    private static PC miPC;
    int posIniReservada, posIni;
    int posActualReservada, posActual;
    int direccionMemoriaReservada=0;
    int direccionMemoriaNormal = 75;
    
    /*
     * Crea una ventana que permite escoger un archivo
     */
    public cargarArchivo() {
        initComponents();
        
        miPC  =  new PC();
        
        inicializarTablas(miPC.getEspacioMemoria(), miPC.getEspacioDisco());
        
        
        
    }

    public static PC getMiPC() {
        return miPC;
    }

    public static void setArchivos(File[] pArchivos) {
        archivos = pArchivos;
    }

    
    //inicializa las filas de la tabla que representa a la memoria
    public static  void inicializarTablas(int espacioMemoria, int espacioDisco){
        for (int i = 0; i < espacioMemoria; i++) {
            tablaMemoria.setValueAt(i, i, 0);
            tablaMemoria.disable();
        }
        
        for (int i = 0; i < espacioDisco; i++) {
            tablaDisco.setValueAt(i, i, 0);
            tablaDisco.disable();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        botSiguiente = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        cargarArchivo = new javax.swing.JButton();
        ejecutar = new javax.swing.JButton();
        botEstadisticas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        axInput = new javax.swing.JTextField();
        bxInput = new javax.swing.JTextField();
        cxInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pcInput = new javax.swing.JTextField();
        acInput = new javax.swing.JTextField();
        irInput = new javax.swing.JTextField();
        dxInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMemoria = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProcesos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDisco = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaejecucion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini PC");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel3.setPreferredSize(new java.awt.Dimension(1280, 720));

        botSiguiente.setText("Siguiente");
        botSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botSiguiente.setBorderPainted(false);
        botSiguiente.setPreferredSize(new java.awt.Dimension(100, 30));
        botSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSiguienteActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limpiar.setBorderPainted(false);
        limpiar.setPreferredSize(new java.awt.Dimension(100, 30));
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        cargarArchivo.setText("Cargar programas");
        cargarArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cargarArchivo.setBorderPainted(false);
        cargarArchivo.setPreferredSize(new java.awt.Dimension(100, 30));
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });

        ejecutar.setText("Ejecutar");
        ejecutar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ejecutar.setBorderPainted(false);
        ejecutar.setPreferredSize(new java.awt.Dimension(100, 30));
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });

        botEstadisticas.setText("Estadisticas");
        botEstadisticas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botEstadisticas.setBorderPainted(false);
        botEstadisticas.setPreferredSize(new java.awt.Dimension(100, 30));
        botEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEstadisticasActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(248, 247, 249));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("AX");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("BX");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("CX");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("DX");

        axInput.setPreferredSize(new java.awt.Dimension(100, 30));
        axInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axInputActionPerformed(evt);
            }
        });

        bxInput.setPreferredSize(new java.awt.Dimension(100, 30));

        cxInput.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("PC");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("AC");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("IR");

        pcInput.setPreferredSize(new java.awt.Dimension(100, 30));

        acInput.setPreferredSize(new java.awt.Dimension(100, 30));

        irInput.setPreferredSize(new java.awt.Dimension(100, 30));
        irInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irInputActionPerformed(evt);
            }
        });

        dxInput.setPreferredSize(new java.awt.Dimension(100, 30));
        dxInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxInputActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("BCP  actual");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pcInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(acInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(irInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(axInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bxInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dxInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(86, 86, 86))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(pcInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(acInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(irInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(axInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(bxInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cxInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(dxInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, pcInput});

        tablaMemoria.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablaMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {"", null},
                {"", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", "Memoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMemoria.setColumnSelectionAllowed(true);
        tablaMemoria.setRowHeight(30);
        tablaMemoria.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tablaMemoria.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaMemoria);
        tablaMemoria.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tablaMemoria.getColumnModel().getColumnCount() > 0) {
            tablaMemoria.getColumnModel().getColumn(0).setMinWidth(40);
            tablaMemoria.getColumnModel().getColumn(0).setPreferredWidth(40);
            tablaMemoria.getColumnModel().getColumn(0).setMaxWidth(40);
            tablaMemoria.getColumnModel().getColumn(1).setResizable(false);
        }

        tablaProcesos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablaProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {"", null, null},
                {"", null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "Nombre", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProcesos.setColumnSelectionAllowed(true);
        tablaProcesos.setRowHeight(30);
        tablaProcesos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tablaProcesos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaProcesos);
        tablaProcesos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tablaProcesos.getColumnModel().getColumnCount() > 0) {
            tablaProcesos.getColumnModel().getColumn(0).setMinWidth(40);
            tablaProcesos.getColumnModel().getColumn(0).setPreferredWidth(40);
            tablaProcesos.getColumnModel().getColumn(0).setMaxWidth(40);
            tablaProcesos.getColumnModel().getColumn(1).setResizable(false);
            tablaProcesos.getColumnModel().getColumn(2).setResizable(false);
        }

        tablaDisco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablaDisco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {"", null},
                {"", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", "Disco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDisco.setColumnSelectionAllowed(true);
        tablaDisco.setRowHeight(30);
        tablaDisco.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tablaDisco.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaDisco);
        tablaDisco.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tablaDisco.getColumnModel().getColumnCount() > 0) {
            tablaDisco.getColumnModel().getColumn(0).setMinWidth(40);
            tablaDisco.getColumnModel().getColumn(0).setPreferredWidth(40);
            tablaDisco.getColumnModel().getColumn(0).setMaxWidth(40);
            tablaDisco.getColumnModel().getColumn(1).setResizable(false);
        }

        tablaejecucion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablaejecucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {"", null},
                {"", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", "asm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaejecucion.setRowHeight(30);
        tablaejecucion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tablaejecucion.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tablaejecucion);
        tablaejecucion.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tablaejecucion.getColumnModel().getColumnCount() > 0) {
            tablaejecucion.getColumnModel().getColumn(0).setMinWidth(40);
            tablaejecucion.getColumnModel().getColumn(0).setPreferredWidth(40);
            tablaejecucion.getColumnModel().getColumn(0).setMaxWidth(40);
            tablaejecucion.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Crea un dialogo con el mensaje indicado
    //id = identificador de error
        // 1 = error de memoria
    public static void mostrarError(int id, String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
        if(id == 1) System.exit(0);

       
    }
    
    private void botSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSiguienteActionPerformed

       /* if(miPC.getInstruccionesbin() == null){//si no se ha seleccionado archivo
            JOptionPane.showMessageDialog(null, "Seleccione un archivo primero");
        }else{
            if(posActual-posIni<miPC.getInstruccionesbin().size()){//mientras que la cantidad de 
                ejecutarInstruccion();                                  //posiciones recorrida se menor que el total de instrucciones
            } else{
                JOptionPane.showMessageDialog(null, "Se han ejecutado todas las instrucciones");
            }
        }  */
    }//GEN-LAST:event_botSiguienteActionPerformed

    //Solicita a miPc la ejecucion de la instruccion
    private void ejecutarInstruccion(){
        String instruccion = tablaMemoria.getValueAt(posActual, 2).toString();
            String[] elementos = instruccion.split(" ");
            String valorAR =Integer.toString(Integer.parseInt(elementos[0],2))
                    + Integer.toString(Integer.parseInt(elementos[1],2))
                    + Integer.toString(Integer.parseInt(elementos[2].substring(1),2));
            irInput.setText(valorAR);
            tablaMemoria.removeRowSelectionInterval(posActual-1, posActual-1);
            tablaMemoria.addRowSelectionInterval(posActual, posActual);
            posActual++;
            if(elementos[0].equals("0011")){//mov
                miPC.ejecutarMov(elementos[1],elementos[2]);
                actualizarInput(elementos[1]);
            }else if(elementos[0].equals("0001")){//LOAD
                miPC.ejecutarLoad(elementos[1]);
                actualizarInput("AC");
            }else if(elementos[0].equals("0101")){//ADD
                miPC.ejecutarAdd(elementos[1]);
                actualizarInput("AC");
            }else if(elementos[0].equals("0100")){//ADD
                miPC.ejecutarSub(elementos[1]);
                actualizarInput("AC");
            }else if(elementos[0].equals("0010")){//ADD
                miPC.ejecutarStore(elementos[1]);
                actualizarInput(elementos[1]);
            }
            pcInput.setText(Integer.toString(posActual));          
            //System.out.println("Largo: "+miPC.getInstruccionesbin().size()+" actual: "+ (posActual-posIni) );
    }
    
    //Luego de la ejecución de la instrucción actualiza la interfaz grafica
    private void actualizarInput(String registro) {
        if (registro.equals("AX")) {//ax
            axInput.setText(Integer.toString(
                    miPC.getRegistros().get(registro).getValor()));
        } else if (registro.equals("BX")) {//bx
            bxInput.setText(Integer.toString(
                    miPC.getRegistros().get(registro).getValor()));
        } else if (registro.equals("CX")) {//cx
            cxInput.setText(Integer.toString(
                    miPC.getRegistros().get(registro).getValor()));
        } else if (registro.equals("DX")) {//dx
            dxInput.setText(Integer.toString(
                    miPC.getRegistros().get(registro).getValor()));
        } else if (registro.equals("AC")) {//ac
            acInput.setText(Integer.toString(
                    miPC.getRegistros().get(registro).getValor()));
        }
    }
    
    
    //Resetea el programa para una nueva ejecucion
    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < 100; i++) {
            tablaMemoria.setValueAt(null, i, 1);
            tablaMemoria.setValueAt(null, i, 2);
        }
        pcInput.setText("");
        acInput.setText("");
        irInput.setText("");
        axInput.setText("");
        bxInput.setText("");
        cxInput.setText("");
        dxInput.setText("");
        
    }//GEN-LAST:event_limpiarActionPerformed

    
    /*
        ejecutar
        Luego de haber cargado el archivo inicia los procesos necesarios para la ejecución de cada instruccion
        -crea la lista de instrucciones asm
        -crea la lista de instrucciones bin
        -escoge una posicion inicial para las instrucciones
    */
    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
        // TODO add your handling code here:
        ArrayList<String[]> instruccionesASM = miPC.getInstruccionesASM();
        if(instruccionesASM == null){
            JOptionPane.showMessageDialog(null, "Seleccione un archivo primero");
        }else{
            int largo = Arrays.asList(instruccionesASM.toArray()).size();
            posIni = Asistente.escogerPosicion(largo);
            posActual = posIni;
            int j = 0;
            for (int i = posIni; j < largo; i++) {
                String instruccionASM = instruccionesASM.get(j)[0]+" "+instruccionesASM.get(j)[1];
                if(instruccionesASM.get(j).length == 3) instruccionASM += " "+instruccionesASM.get(j)[2];
                tablaMemoria.setValueAt( instruccionASM, i, 1);
                j++;
            }

            //tablaMemoria.addRowSelectionInterval(posIni, posIni);
            pcInput.setText(Integer.toString(posIni));
            tablaMemoria.scrollRectToVisible(new Rectangle(tablaMemoria.getCellRect(posIni+9, 0, true)));
        }
        miPC.setInstruccionesASM(instruccionesASM);

    }//GEN-LAST:event_ejecutarActionPerformed

    //Seleccionar archivo
    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed
        archivoValido = false;
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        chooser.showOpenDialog(cargarArchivo);
        archivos = chooser.getSelectedFiles();
        for (File archivo : archivos) {
            System.out.println(archivo.getName());
        }
        try {
            ArrayList<ArrayList<String[]>> archivosValidados = Asistente.validarArchivos(archivos);
            if(archivosValidados != null){
                try {
                    cargarEnDisco(archivosValidados);
                    inicializarMemoria();
                } catch (InterruptedException ex) {
                    Logger.getLogger(cargarArchivo.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            

        } catch (IOException ex) {
            Logger.getLogger(cargarArchivo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cargarArchivoActionPerformed

    public void inicializarMemoria(){
        int cantProcesosEjecutar = 5;
        
        for(int proceso =0; proceso <5 && proceso < archivos.length; proceso++){
            
            BCP actual = miPC.getBCPat(proceso);
            actual.setSiguienteBPC(direccionMemoriaReservada+16);
            String idProceso = actual.getIdentificador();
            tablaMemoria.setValueAt("identificador: "+idProceso, direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            tablaMemoria.setValueAt("estado "+idProceso+": "+actual.getEstado(), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            
            String[] archivoActual = getArchivoFromDisco(idProceso);
            actual.setPC(direccionMemoriaNormal);
            for(String instruccion : archivoActual){
                tablaMemoria.setValueAt(instruccion ,direccionMemoriaNormal, 1);
                direccionMemoriaNormal++;
            }
            tablaMemoria.setValueAt("Contador (PC) "+idProceso+": "+actual.getPC(), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            
            tablaMemoria.setValueAt("Pila 0 "+idProceso+": "+actual.getPila().get(0), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            tablaMemoria.setValueAt("Pila 1 "+idProceso+": "+actual.getPila().get(1), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            tablaMemoria.setValueAt("Pila 2 "+idProceso+": "+actual.getPila().get(2), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            tablaMemoria.setValueAt("Pila 3 "+idProceso+": "+actual.getPila().get(3), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            tablaMemoria.setValueAt("Pila 4 "+idProceso+": "+actual.getPila().get(4), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            
            tablaMemoria.setValueAt("Cpu actual "+idProceso+": "+actual.getCpuActual() , direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            
            tablaMemoria.setValueAt("inicio "+idProceso+": "+actual.getTiempoInicio(), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            tablaMemoria.setValueAt("empleado "+idProceso+": "+actual.getTiempoEmpleado(), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            
            tablaMemoria.setValueAt("Estado interrupcion  "+idProceso+": "+actual.getEstadoInterrupcion(), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            
            
            tablaMemoria.setValueAt("siguiente BCP  "+idProceso+": "+actual.getSiguienteBPC(), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            
            actual.setBase(actual.getPC());
            tablaMemoria.setValueAt("Base  "+idProceso+": "+actual.getBase(), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            
            actual.setAlcance(archivoActual.length);
            tablaMemoria.setValueAt("Alcance  "+idProceso+": "+actual.getAlcance(), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            
            tablaMemoria.setValueAt("Prioridad  "+idProceso+": "+actual.getPrioridad(), direccionMemoriaReservada, 1);
            direccionMemoriaReservada++;
            
            miPC.setBCPat(proceso, actual);
            
        }
    }
    
    public String[] getArchivoFromDisco(String idProceso) {
        System.out.println("getArchivoFromDisco");
        for(int i = 0;i< posActualReservada;i++){
            String[] valorFila = tablaDisco.getValueAt(i, 1).toString().split(",");
         
            String idArchivo =valorFila[0];
            int inicioArchivo = Integer.parseInt(valorFila[1].trim());
            int finArchivo = Integer.parseInt(valorFila[2].trim());
            System.out.println(valorFila[0]);
            System.out.println(inicioArchivo);
            System.out.println(finArchivo);
            
             
            if(idProceso.equals(valorFila[0])){
                String[] archivo = new String[finArchivo-inicioArchivo+1];
                int cont = 0;
                for(int j = inicioArchivo; j<=finArchivo;j++){
                    String instruccionString = tablaDisco.getValueAt(j, 1).toString();
                    System.out.println(instruccionString);
                    archivo[cont] = instruccionString;
                    cont++;
                }
                return archivo;
            }
            
        }
        
        
        return null;
        
    }
    
    public void cargarEnDisco(ArrayList<ArrayList<String[]>> archivosValidados ) throws InterruptedException{
        
            posIni = archivos.length + 10;
            posActual = posIni;
            posIniReservada = 0;
            posActualReservada = 0;
            System.out.println(archivosValidados.size());
            int i = 0;
            for (ArrayList<String[]> archivo : archivosValidados) {
                System.out.println(archivos[i].getName());
                System.out.println(Arrays.deepToString(archivo.toArray()));
                System.out.println("Cantidad de archivos: " + archivos.length);
                String temp = archivos[i].getName() + "," + Integer.toString(posActual) + ", " + Integer.toString(posActual + archivo.size()-1);
                tablaDisco.setValueAt(temp, posActualReservada, 1);
                
                crearBCP(archivos[i].getName(),posActualReservada);
                posActualReservada++;

                for (String[] instruccion : archivo) {
                    String strInstruccion = instruccion[0];
                    if (instruccion.length > 1) {
                        strInstruccion += " ";
                        for (int j = 1; j < instruccion.length; j++) {
                            strInstruccion += instruccion[j] + ", ";
                        }
                        strInstruccion = strInstruccion.substring(0, strInstruccion.length() - 2);
                    }
                    
          
                    tablaDisco.setValueAt(strInstruccion, posActual, 1);
                    posActual++;

                }

                //posActual += archivo.size()+1;
                i++;
                //TimeUnit.SECONDS.sleep(1);
            }  
            
    }
    
    public void crearBCP(String nombre, int numeroBCP){
        BCP bcpNuevo = new BCP(nombre);
        miPC.addBCP(bcpNuevo);
        tablaProcesos.setValueAt(numeroBCP, numeroBCP, 0);
        tablaProcesos.setValueAt(nombre, numeroBCP, 1);
        tablaProcesos.setValueAt(miPC.getBcps().get(numeroBCP).getEstado(), numeroBCP, 2);
       
    }
    
    private void botEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEstadisticasActionPerformed
        // TODO add your handling code here:
        System.out.println(tablaDisco.getValueAt(0, 1));
    }//GEN-LAST:event_botEstadisticasActionPerformed

    private void dxInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dxInputActionPerformed

    private void irInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irInputActionPerformed

    private void axInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_axInputActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cargarArchivo().setVisible(true);
                
                
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acInput;
    private javax.swing.JTextField axInput;
    private javax.swing.JButton botEstadisticas;
    private javax.swing.JButton botSiguiente;
    private javax.swing.JTextField bxInput;
    private javax.swing.JButton cargarArchivo;
    private javax.swing.JTextField cxInput;
    private javax.swing.JTextField dxInput;
    private javax.swing.JButton ejecutar;
    private javax.swing.JTextField irInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField pcInput;
    public static javax.swing.JTable tablaDisco;
    public static javax.swing.JTable tablaMemoria;
    public static javax.swing.JTable tablaProcesos;
    public static javax.swing.JTable tablaejecucion;
    // End of variables declaration//GEN-END:variables
}
